version: "1"
projects:
- name: platform-ads-project
  environments:
  - name: Production
    services:
    - type: web
      name: platform-ads-server
      runtime: node
      repo: https://github.com/platform-ads/platform-ads-server
      plan: free
      envVars:
      - key: JWT_REFRESH_EXPIRES_IN
        sync: false
      - key: JWT_EXPIRES_IN
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_PHONE
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: MONGODB_DB_NAME
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: PORT
        sync: false
      - key: NODE_ENV
        sync: false
      region: singapore
      buildCommand: yarn; yarn build
      startCommand: yarn start:prod
      autoDeployTrigger: commit
      previews:
        generation: automatic
